export const GET_USER_DATA = 'GET_USER_DATA';
export const SET_USER_DATA = 'SET_USER_DATA';
export const KEY = 'userDat';
export const SET_MARVEL_CHARACTERS = 'SET_MARVEL_CHARACTERS';
export const SET_SEARCHED_MARVEL_CHARACTERS = 'SET_SEARCHED_MARVEL_CHARACTERS';